### ISSUE TITLE
Missing commands/events

### ISSUE THREAD

**Issue by user010100011110** [foxxyz/node-clementine-client#1]
Added some missing commands/events for playlist songs, lyrics and shuffle mode. Extended client.js attached.

[client.js.zip](https://github.com/foxxyz/node-clementine-client/files/2591914/client.js.zip)

**Comment by foxxyz** [comment]
Wow, I'm really sorry, but I missed this issue. Could you resubmit the changes as a PR?

**Comment by foxxyz** [comment]
Closing...
